<div class="container-fluid">
    <div class="block-header">
        <h2>Settings > General Settings</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-4 col-md-4 float-left">
            <div class="card">
                <div class="header">
                    <h2>User Settings</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success user-settings-alert"></div>
                    <form class="user-settings" method="POST">
                        <label for="maintenance_mode">Maintenance Mode <span class="black" data-toggle="popover" data-trigger="hover" data-content="Turn the whole site under Maintenance. You can get the site back by visiting <?php echo $wo['config']['uri'].'/?access=admin'; ?>"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="maintenance_mode" id="maintenance_mode-enabled" value="1" <?php echo ($wo['config']['maintenance_mode'] == 1) ? 'checked': '';?>>
                            <label for="maintenance_mode-enabled">Enabled</label>
                            <input type="radio" name="maintenance_mode" id="maintenance_mode-disabled" value="0" <?php echo ($wo['config']['maintenance_mode'] == 0) ? 'checked': '';?>>
                            <label for="maintenance_mode-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="pro_system">Pro system<span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow premium account."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="pro_system" id="pro_system-enabled" value="1" <?php echo ($wo['config']['pro_system'] == '1') ? 'checked': '';?>>
                            <label for="pro_system-enabled">Enabled</label>
                            <input type="radio" name="pro_system" id="pro_system-disabled" value="0" <?php echo ($wo['config']['pro_system'] == '0') ? 'checked': '';?>>
                            <label for="pro_system-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="emailValidation">Account Validation <span class="black" data-toggle="popover" data-trigger="hover" data-content="Send activation link when user has registered"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="emailValidation" id="emailValidation-enabled" value="1" <?php echo ($wo['config']['emailValidation'] == 1) ? 'checked': '';?>>
                            <label for="emailValidation-enabled">Enabled</label>
                            <input type="radio" name="emailValidation" id="emailValidation-disabled" value="0" <?php echo ($wo['config']['emailValidation'] == 0) ? 'checked': '';?>>
                            <label for="emailValidation-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="sms_or_email">Account Validation System<span class="black" data-toggle="popover" data-trigger="hover" data-content="Choose the validation type, by SMS or E-mail, if you choose SMS, make sure you have configured the SMS configration."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="sms_or_email" id="sms_or_email-enabled" value="sms" <?php echo ($wo['config']['sms_or_email'] == 'sms') ? 'checked': '';?>>
                            <label for="sms_or_email-enabled">SMS</label>
                            <input type="radio" name="sms_or_email" id="sms_or_email-disabled" value="mail" <?php echo ($wo['config']['sms_or_email'] == 'mail') ? 'checked': '';?>>
                            <label for="sms_or_email-disabled" class="m-l-20">E-mail</label>
                        </div>
                        <label for="deleteAccount">User Account Deletion <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow users to delete their account"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="deleteAccount" id="deleteAccount-enabled" value="1" <?php echo ($wo['config']['deleteAccount'] == 1) ? 'checked': '';?>>
                            <label for="deleteAccount-enabled">Enabled</label>
                            <input type="radio" name="deleteAccount" id="deleteAccount-disabled" value="0" <?php echo ($wo['config']['deleteAccount'] == 0) ? 'checked': '';?>>
                            <label for="deleteAccount-disabled" class="m-l-20">Disabled</label>
                        </div>

                        <label for="user_registration">Default avatar</label><div class="clearfix"></div><br>
                        <div class="form-group form-float">
                            <div class="form-line focused">
                                <input type="text" name="userDefaultAvatar" class="form-control" value="<?php echo $wo['config']['userDefaultAvatar']?>">
                                <label class="form-label">path after : <?php echo $wo['config']['site_url']?>/</label>
                            </div>
                        </div>

                        <label for="user_registration">Profile avatar crop settings</label><div class="clearfix"></div><br>
                        <div class="form-group form-float">
                            <div class="form-line focused">
                                <input type="text" name="profile_picture_width_crop" class="form-control" value="<?php echo $wo['config']['profile_picture_width_crop']?>">
                                <label class="form-label">width</label>
                            </div>
                            <br>
                            <div class="form-line focused">
                                <input type="text" name="profile_picture_height_crop" class="form-control" value="<?php echo $wo['config']['profile_picture_height_crop']?>">
                                <label class="form-label">height</label>
                            </div>
                            <br>
                            <div class="form-line focused">
                                <input type="text" name="profile_picture_image_quality" class="form-control" value="<?php echo $wo['config']['profile_picture_image_quality']?>">
                                <label class="form-label">quality ~50:100</label>
                            </div>
                        </div>

                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4 float-left">
            <div class="card">
                <div class="header">
                    <h2>General Settings</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success general-settings-alert"></div>
                    <form class="general-settings" method="POST">
                        <label for="maintenance_mode">Google Place API <span class="black" data-toggle="popover" data-trigger="hover" data-content="Profile settings - location field auto complete"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <br><br><div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="google_place_api" name="google_place_api" class="form-control" value="<?php echo $wo['config']['google_place_api'];?>">
                                <label class="form-label">Profile settings <small>- location field auto complete</small></label>
                            </div>
                            <small>You can disable it by empty this text</small>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line focused">
                                <input type="text" name="max_swaps" class="form-control" value="<?php echo $wo['config']['max_swaps']?>">
                                <label class="form-label">Max likes/swipes per day</label>
                            </div>
                            <br>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line focused">
                                <input type="text" name="img_blur_amount" class="form-control" value="<?php echo $wo['config']['img_blur_amount']?>">
                                <label class="form-label">Private image blur percentage ( 0 : 100 ) </label>
                            </div>
                            <br>
                        </div>

                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <!--
        <div class="col-lg-4 col-md-4 float-right">
            <div class="card">
                <div class="header">
                    <h2>Chat Settings</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success chat-settings-alert"></div>
                    <form class="chat-settings" method="POST">
                        <label for="chatSystem">Chat System <span class="black" data-toggle="popover" data-trigger="hover" data-content="Enable chat system to chat with friends on the buttom of the page."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="chatSystem" id="chatSystem-enabled" value="1" <?php echo ($wo['config']['load_config_in_session'] == 1) ? 'checked': '';?>>
                            <label for="chatSystem-enabled">Enabled</label>
                            <input type="radio" name="chatSystem" id="chatSystem-disabled" value="0" <?php echo ($wo['config']['load_config_in_session'] == 0) ? 'checked': '';?>>
                            <label for="chatSystem-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="message_seen">Message Seen Alert <span class="black" data-toggle="popover" data-trigger="hover" data-content="Checks if the message was seen in chat system, Recommended for powerful servers"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="message_seen" id="message_seen-enabled" value="1" <?php echo ($wo['config']['load_config_in_session'] == 1) ? 'checked': '';?>>
                            <label for="message_seen-enabled">Enabled</label>
                            <input type="radio" name="message_seen" id="message_seen-disabled" value="0" <?php echo ($wo['config']['load_config_in_session'] == 0) ? 'checked': '';?>>
                            <label for="message_seen-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="message_typing">Typing System<span class="black" data-toggle="popover" data-trigger="hover" data-content="Checks if the user is typing in chat system, Recommended for powerful servers"><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="message_typing" id="message_typing-enabled" value="1" <?php echo ($wo['config']['load_config_in_session'] == '1') ? 'checked': '';?>>
                            <label for="message_typing-enabled">Enabled</label>
                            <input type="radio" name="message_typing" id="message_typing-disabled" value="0" <?php echo ($wo['config']['load_config_in_session'] == '0') ? 'checked': '';?>>
                            <label for="message_typing-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4 float-right">
            <div class="card">
                <div class="header">
                    <h2 class="pull-left">Upload Settings</h2></a>
                    <div class="clearfix"></div>
                </div>
                <div class="body">
                    <div class="alert alert-success upload-settings-alert"></div>
                    <form class="upload-settings" method="POST">
                        <label for="fileSharing">File Sharing <span class="black" data-toggle="popover" data-trigger="hover" data-content="Share & upload videos,images,files,sounds, etc.."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="fileSharing" id="fileSharing-enabled" value="1" <?php echo ($wo['config']['load_config_in_session'] == 1) ? 'checked': '';?>>
                            <label for="fileSharing-enabled">Enabled</label>
                            <input type="radio" name="fileSharing" id="fileSharing-disabled" value="0" <?php echo ($wo['config']['load_config_in_session'] == 0) ? 'checked': '';?>>
                            <label for="fileSharing-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="video_upload">Video Upload <span class="black" data-toggle="popover" data-trigger="hover" data-content="Enable video upload to share & upload videos to the site."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="video_upload" id="video_upload-enabled" value="1" <?php echo ($wo['config']['load_config_in_session'] == 1) ? 'checked': '';?>>
                            <label for="video_upload-enabled">Enabled</label>
                            <input type="radio" name="video_upload" id="video_upload-disabled" value="0" <?php echo ($wo['config']['load_config_in_session'] == 0) ? 'checked': '';?>>
                            <label for="video_upload-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="audio_upload">Audio Upload <span class="black" data-toggle="popover" data-trigger="hover" data-content="Enable audio upload to share & upload music to the site."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="audio_upload" id="audio_upload-enabled" value="1" <?php echo ($wo['config']['load_config_in_session'] == 1) ? 'checked': '';?>>
                            <label for="audio_upload-enabled">Enabled</label>
                            <input type="radio" name="audio_upload" id="audio_upload-disabled" value="0" <?php echo ($wo['config']['load_config_in_session'] == 0) ? 'checked': '';?>>
                            <label for="audio_upload-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <label for="css_upload">CSS Upload <span class="black" data-toggle="popover" data-trigger="hover" data-content="Allow users to upload their own CSS file to design their profile."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="css_upload" id="css_upload-enabled" value="1" <?php echo ($wo['config']['load_config_in_session'] == 1) ? 'checked': '';?>>
                            <label for="css_upload-enabled">Enabled</label>
                            <input type="radio" name="css_upload" id="css_upload-disabled" value="0" <?php echo ($wo['config']['load_config_in_session'] == 0) ? 'checked': '';?>>
                            <label for="css_upload-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="allowedExtenstion" name="allowedExtenstion" class="form-control" value="<?php echo $wo['config']['load_config_in_session']?>">
                                <label class="form-label">Allowed extenstions (separated with comma,)</label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="mime_types" name="mime_types" class="form-control" value="<?php echo $wo['config']['load_config_in_session']?>">
                                <label class="form-label">Allowed MIME Types (separated with comma,)</label>
                            </div>
                        </div>
                        <label for="maxUpload">Max upload size for videos, images, sounds, and files</label>
                        <select class="form-control show-tick" id="maxUpload" name="maxUpload">
                              <option value="2000000"    <?php echo ($wo['config']['load_config_in_session'] == 2000000)   ? ' selected': '';?>>2 MB</option>
                              <option value="6000000"    <?php echo ($wo['config']['load_config_in_session'] == 6000000)   ? ' selected': '';?>>6 MB</option>
                              <option value="12000000"   <?php echo ($wo['config']['load_config_in_session'] == 12000000)  ? ' selected': '';?>>12 MB</option>
                              <option value="24000000"   <?php echo ($wo['config']['load_config_in_session'] == 24000000)  ? ' selected': '';?>>24 MB</option>
                              <option value="48000000"   <?php echo ($wo['config']['load_config_in_session'] == 48000000)  ? ' selected': '';?>>48 MB</option>
                              <option value="96000000"   <?php echo ($wo['config']['load_config_in_session'] == 96000000)  ? ' selected': '';?>>96 MB</option>
                              <option value="256000000"  <?php echo ($wo['config']['load_config_in_session'] == 256000000) ? ' selected': '';?>>256 MB</option>
                              <option value="512000000"  <?php echo ($wo['config']['load_config_in_session'] == 512000000) ? ' selected': '';?>>512 MB</option>
                              <option value="1000000000" <?php echo ($wo['config']['load_config_in_session'] == 1000000000) ? ' selected': '';?>>1 GB</option>
                              <option value="5000000000" <?php echo ($wo['config']['load_config_in_session'] == 5000000000) ? ' selected': '';?>>5 GB</option>
                              <option value="10000000000" <?php echo ($wo['config']['load_config_in_session'] == 10000000000) ? ' selected': '';?>>10 GB</option>
                        </select>
                        <div class="clearfix"></div>
                        <br><br>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>

                    </form>
                </div>
            </div>
        </div>        -->
        <div class="col-lg-4 col-md-4 float-right">
            <div class="card">
                <div class="header">
                    <h2>Notifications Settings</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success notifications-settings-alert"></div>
                    <form class="notifications-settings" method="POST">
                        <label for="emailNotification">Email Notifications <span class="black" data-toggle="popover" data-trigger="hover" data-content="Send user notifications via email."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="emailNotification" id="emailNotification-enabled" value="1" <?php echo ($wo['config']['emailNotification'] == 1) ? 'checked': '';?>>
                            <label for="emailNotification-enabled">Enabled</label>
                            <input type="radio" name="emailNotification" id="emailNotification-disabled" value="0" <?php echo ($wo['config']['emailNotification'] == 0) ? 'checked': '';?>>
                            <label for="emailNotification-disabled" class="m-l-20">Disabled</label>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>


        <div class="col-lg-4 col-md-4 float-right">
            <div class="card">
                <div class="header">
                    <h2>Activation Settings</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success activation-settings-alert"></div>
                    <form class="activation-settings" method="POST">
                        <label for="activation_limit_system">Activation Limits <span class="black" data-toggle="popover" data-trigger="hover" data-content="user activation limits between sending new SMS or email."><i class="fa fa-question-circle fa-fw"></i></span></label>
                        <div class="form-group">
                            <input type="radio" name="activation_limit_system" id="activation_limit_system-enabled" value="1" <?php echo ($wo['config']['activation_limit_system'] == 1) ? 'checked': '';?>>
                            <label for="activation_limit_system-enabled">Enabled</label>
                            <input type="radio" name="activation_limit_system" id="activation_limit_system-disabled" value="0" <?php echo ($wo['config']['activation_limit_system'] == 0) ? 'checked': '';?>>
                            <label for="activation_limit_system-disabled" class="m-l-20">Disabled</label>
                        </div>

                        <label for="user_registration">Time Limit & Request Settings</label><div class="clearfix"></div><br>
                        <div class="form-group form-float">
                            <div class="form-line focused">
                                <input type="text" name="max_activation_request" class="form-control" value="<?php echo $wo['config']['max_activation_request']?>">
                                <label class="form-label">Max requests per user</label>
                            </div>
                            <br>
                            <div class="form-line focused">
                                <input type="text" name="activation_request_time_limit" class="form-control" value="<?php echo $wo['config']['activation_request_time_limit']?>">
                                <label class="form-label">Time between requests (in minutes)</label>
                            </div>
                        </div>


                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    var form_general_settings = $('form.general-settings');
    form_general_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
        beforeSend: function() {
            form_general_settings.find('button').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
            	form_general_settings.find('button').text('Save');
            	$('.general-settings-alert').html('<i class="fa fa-check"></i> Settings updated successfully');
            	setTimeout(function () {
            		$('.general-settings-alert').empty();
            	}, 2000);
            }
        }
    });


    var form_user_settings = $('form.user-settings');
    form_user_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
        beforeSend: function() {
            form_user_settings.find('button').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_user_settings.find('button').text('Save');
                $('.user-settings-alert').html('<i class="fa fa-check"></i> Settings updated successfully');
                setTimeout(function () {
                    $('.user-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_chat_settings = $('form.chat-settings');
    form_chat_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
        beforeSend: function() {
            form_chat_settings.find('button').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_chat_settings.find('button').text('Save');
                $('.chat-settings-alert').html('<i class="fa fa-check"></i> Settings updated successfully');
                setTimeout(function () {
                    $('.chat-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_notifications_settings = $('form.notifications-settings');
    form_notifications_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
        beforeSend: function() {
            form_notifications_settings.find('button').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_notifications_settings.find('button').text('Save');
                $('.notifications-settings-alert').html('<i class="fa fa-check"></i> Settings updated successfully');
                setTimeout(function () {
                    $('.notifications-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_activation_settings = $('form.activation-settings');
    form_activation_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
        beforeSend: function() {
            form_activation_settings.find('button').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_activation_settings.find('button').text('Save');
                $('.activation-settings-alert').html('<i class="fa fa-check"></i> Settings updated successfully');
                setTimeout(function () {
                    $('.activation-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_upload_settings = $('form.upload-settings');
    form_upload_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
        beforeSend: function() {
            form_upload_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_upload_settings.find('.waves-effect').text('Save');
                $('.upload-settings-alert').html('<i class="fa fa-check"></i> Settings updated successfully');
                setTimeout(function () {
                    $('.upload-settings-alert').empty();
                }, 2000);
            }
        }
    });
});

</script>